#!/usr/bin/env bash
set -e

SED=sed
BACKLOG_COLUMN="Backlog"
BACKLOG="Build Team Kanban Board"
LABEL=bug
OPENSHIFTIO_REPO_ISSUE=openshiftio/openshift.io

type -p gsed 2>/dev/null >/dev/null && SED=gsed
assignme="--me"

function green() { msg="$@";echo "\e[40;38;5;82m${msg}\e[0m" ;}
function red() { msg="$@";echo "\e[40;91;5;82m${msg}\e[0m" ;}
function yellow() { msg="$@";echo "\e[40;91;5;93m${msg}\e[0m" ;}
function cyan() { msg="$@";echo "\e[40;91;5;96m${msg}\e[0m" ;}

function help() {
    echo "-l=LABEL -i[in progress] -n[no_assignme] -j[justopenshiftio]"
}

while getopts ":l:inj" opt; do
    case $opt in
        j)
            justopenshiftio=yes
            REPO=${OPENSHIFTIO_REPO_ISSUE}
            ;;
        n)
            assignme=""
            ;;
        l)
            LABEL=${OPTARG}
            ;;
        i)
            BACKLOG_COLUMN="In progress"
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            help
            exit 1
            ;;
    esac
done

shift $((OPTIND-1))

REPO=${REPO:-"$1"}

[[ -z ${REPO} ]] && { echo "I need a upstream repo"; help; exit 1 ;}

if [[ $LABEL == "bug" ]];then
    osiolabel="type/bug"
elif [[ $LABEL == feature ]];then
    osiolabel="type/task"
else
    echo "invalid label $LABEL"
    exit 1
fi

echo -e "$(cyan Openshiftio): ${OPENSHIFTIO_REPO_ISSUE}"
[[ -z ${justopenshiftio} ]] && echo -e "$(cyan Upstream): $(red $REPO)"
[[ -z ${justopenshiftio} ]] && echo -e "$(cyan Label): $(yellow $LABEL)"
echo -e "$(cyan OSIO Label): $osiolabel"
echo -e "$(cyan Backlog): ${BACKLOG}"
echo -e "$(cyan Column): ${BACKLOG_COLUMN}"
[[ -n ${assignme} ]] && echo -e "$(cyan Assigned): $(red me)"

echo

read -n 1 -p "Are you OK with these?: " REPLY
[[ ${REPLY,,} != y ]] && exit

echo
echo

tempf=$(mktemp) || exit
trap "rm -f -- $tempf" EXIT

if [[ ${justopenshiftio} ]];then
    LABELS="-l area/pipelines -l sprint/current -l team/build-cd -l ${osiolabel}"
else
    LABELS="-l ${LABEL}"
fi

REPO_URL=$(github-issue-cli ${assignme} --output-file ${tempf} ${LABELS} ${REPO} 2>/dev/null)

if [[ -n ${justopenshiftio} ]];then
    OPENSHIFTIO_URL=${REPO_URL}
else
    labelp=$(basename ${REPO}|${SED} -e 's/-/ /g' -e 's/[^ _-]*/\u&/g')
    ${SED} -i -e "1 s/^/${labelp/Fabric8 }: /" -e "/# Everything starting/i\\${labelp} issue: ${REPO_URL}" ${tempf}
    OPENSHIFTIO_URL=$(github-issue-cli \
                      -n --input-file ${tempf} \
                      -l area/pipelines -l team/build-cd -l ${osiolabel} \
                      ${assignme} ${OPENSHIFTIO_REPO_ISSUE})
fi

if type -p colout >/dev/null 2>/dev/null;then
    github-project-cli -o fabric8io -b "${BACKLOG}" -c "${BACKLOG_COLUMN}" -i "${OPENSHIFTIO_URL}"|colout '(https://\S*).*on (https://\S*).*in "([^"]+)" column' yellow,blue,red
else
    github-project-cli -o fabric8io -b "${BACKLOG}" -c "${BACKLOG_COLUMN}" -i "${OPENSHIFTIO_URL}"
fi

echo

echo -e "$(red OpenShiftIO URL): ${OPENSHIFTIO_URL}"
[[ -z ${justopenshiftio} ]] && echo -e "$(red ${labelp} URL): ${REPO_URL}"
